### ISSUE TITLE
Python Script Error

### ISSUE THREAD

**Issue by evanshoshan** [randomt4sk/plugin.program.autocompletion#2]
This is the log error I get when I try to click on a suggestion.

15:37:46.817 T:18446744072519823472   ERROR: PlayMedia could not play media: plugin://plugin.program.autocompletion/?info=selectautocomplete&&id=game of thrones
15:37:46.901 T:18446744072563184192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /jsonrpc?request=%7B%22params%22%3A+%7B%22text%22%3A+%22game+of+thrones%22%2C+%22done%22%3A+false%7D%2C+%22jsonrpc%22%3A+%222.0%22%2C+%22method%22%3A+%22Input.SendText%22%2C+%22id%22%3A+1%7D (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xbbad2b78>: Failed to establish a new connection: [Errno 111] Connection refused',))
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py", line 121, in <module>
                                                Main()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py", line 98, in __init__
                                                start_info_actions(self.infos, self.params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py", line 43, in start_info_actions
                                                get_xbmc_json(method="Input.SendText",params={"text":params.get("id"),"done":False})
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py", line 28, in get_xbmc_json
                                                headers=headers)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 70, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 56, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 488, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 609, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 487, in send
                                                raise ConnectionError(e, request=request)
                                            ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /jsonrpc?request=%7B%22params%22%3A+%7B%22text%22%3A+%22game+of+thrones%22%2C+%22done%22%3A+false%7D%2C+%22jsonrpc%22%3A+%222.0%22%2C+%22method%22%3A+%22Input.SendText%22%2C+%22id%22%3A+1%7D (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xbbad2b78>: Failed to establish a new connection: [Errno 111] Connection refused',))
                                            -->End of Python script error report<--
15:37:51.776 T:18446744072519823472   ERROR: PlayMedia could not play media: plugin://plugin.program.autocompletion/?info=selectautocomplete&&id=game of thrones
15:37:51.829 T:18446744071961979760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /jsonrpc?request=%7B%22params%22%3A+%7B%22text%22%3A+%22game+of+thrones%22%2C+%22done%22%3A+false%7D%2C+%22jsonrpc%22%3A+%222.0%22%2C+%22method%22%3A+%22Input.SendText%22%2C+%22id%22%3A+1%7D (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xbbbb07e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py", line 121, in <module>
                                                Main()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py", line 98, in __init__
                                                start_info_actions(self.infos, self.params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py", line 43, in start_info_actions
                                                get_xbmc_json(method="Input.SendText",params={"text":params.get("id"),"done":False})
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autocompletion/plugin.py", line 28, in get_xbmc_json
                                                headers=headers)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 70, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 56, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 488, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 609, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 487, in send
                                                raise ConnectionError(e, request=request)
                                            ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /jsonrpc?request=%7B%22params%22%3A+%7B%22text%22%3A+%22game+of+thrones%22%2C+%22done%22%3A+false%7D%2C+%22jsonrpc%22%3A+%222.0%22%2C+%22method%22%3A+%22Input.SendText%22%2C+%22id%22%3A+1%7D (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xbbbb07e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
                                            -->End of Python script error report<--

**Comment by GitCuppaJoe** [comment]
My issue was that I set a password for port 8080. Settings -> services -> control -> password. Although not a great solution because I use the yatse app, it worked for me. If I have time I can try and incorporate a password fix. Hopefully that solves your issue.

**Comment by randomt4sk** [comment]
Hello mates,
sorry for long inactivity.
I totally forgot about passwords.
This issue was hopefully fixed today.
